sudo: false

language: node_js

node_js:
 - 0.10
 - 0.12
 - 4
 - 5

cache:
  directories:
    - node_modules

before_script:
  - npm prune

after_success:
  - curl -Lo travis_after_all.py https://git.io/travis_after_all
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - npm run coverage
  - npm run codeclimate

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
